#pragma once

#include "../dimension.h"
#include "../gradient2D.h"
#include "../matrix.h"
#include "../plane.h"
#include "../point2D.h"
#include "../shape/circle.h"
#include "../shape/polygon.h"
#include "../shape/rectangle.h"
#include "../shape/triangle.h"
#include "../vector/vector.h"
#include "../vector/vector2d.h"
#include "../vector/vector3d.h"
#include "../vector/vector4d.h"