name: Build

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
     - '**/*.md'
     - '**/*.bat'
     - '**/*.sh'
     - '**/*.html'  # Documentation
     - '**/*.js'
     - '**/*.png'
     - '**/*.css'
     - '**/*.dox'
     - '**/*.svg'
     - '**/*.bmp'
     - '**/*.ico'

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    strategy:
      matrix:
        operatingsystems: [windows-latest, ubuntu-latest] 
        buildtypes: [Release] 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          cmake \
          file \
          fonts-dejavu-core \
          libfreetype-dev \
          libharfbuzz-dev \
          libflac-dev \
          libfluidsynth-dev \
          libgme-dev \
          libmpg123-dev \
          libopusfile-dev \
          libvorbis-dev \
          libxmp-dev \
          libwavpack-dev \
          pkg-config \
          ${NULL+}
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Building Core
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target tobot-core