name: Build

on:
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**/*.md"
      - "**/*.bat"
      - "**/*.sh"
      - "**/*.html" # Documentation
      - "**/*.js"
      - "**/*.png"
      - "**/*.css"
      - "**/*.dox"
      - "**/*.svg"
      - "**/*.bmp"
      - "**/*.ico"

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    strategy:
      matrix:
        operatingsystems: [windows-latest]
        buildtypes: [Release]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

      - name: Building Engine
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target tobot-engine
