name: Build project

on:
  push:
    branches: [ "build-workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    strategy:
      matrix:
        operatingsystems: [windows-latest, ubuntu-latest, macos-latest] 
        buildtypes: [Release] 

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    # include submodules
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Building project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target project-farscape